name: celmouse

packages:
  - mobile
  - desktop
  - packages/**
  - plugins/**

scripts:
  clean: melos clean && melos bootstrap

  protocol:
    run: melos exec --scope="*protocol*" -- dart run build_runner build --delete-conflicting-outputs