name: _
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  ## Packages
  - packages/protocol/keyboard_protocol
  - packages/protocol/mouse_protocol
  - packages/protocol/protocol
  - packages/protocol/protocol_interface

  ## Plugins
  - plugins/keyboard/keyboard
  - plugins/keyboard/keyboard_macos
  - plugins/keyboard/keyboard_platform_interface
  - plugins/mouse/mouse
  - plugins/mouse/mouse_linux
  - plugins/mouse/mouse_macos
  - plugins/mouse/mouse_platform_interface
  - plugins/mouse/mouse_windows
