name: server
description: "Desktop HUB for Celmouse App"
publish_to: 'none'
version: 2.0.0+1
  
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  mouse:
    path: ../plugins/mouse/mouse
  
  protocol:
    path: ../packages/protocol
  
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  desktop_window: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate:
    - platform: windows
      build:
        exe_name: celmouse
